; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "QMultiUnit"
#define MyAppVersion "1.0.0"
#define MyAppPublisher "Matthew Yang (杨佳明)"
#define MyAppURL "https://www.github.com/matthewyang204/QMultiUnit"
#define MyAppExeName "QMultiUnit.exe"

; Search for the executable in several possible build directories.
#if FileExists("..\build\" + MyAppExeName)
    #define MyAppExeDir "..\build"
#elif FileExists("..\src\build\" + MyAppExeName)
    #define MyAppExeDir "..\src\build"
#elif FileExists("..\src\build\Release\" + MyAppExeName)
    #define MyAppExeDir "..\src\build\Release"
#else
    #error Could not find executable in any expected build directory.
#endif

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{0472C2A1-9C78-4C40-A93B-45224215B05C}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DisableProgramGroupPage=yes
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputBaseFilename=qmultiunit-{#MyAppVersion}-setup
SetupIconFile=..\src\images\QMultiUnit.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Files]
Source: "{#MyAppExeDir}\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#MyAppExeDir}\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent